### ISSUE TITLE
Add OnViewChanged Event Handler

### ISSUE THREAD

**Issue by TimPurdum** [dymaptic/GeoBlazor#91]
Brought up during [this Discord discussion](https://discord.com/channels/1027907220949717033/1031452704167432222). User `Sipowicz` offered some sample implementation.

Add event listeners in `arcGisInterop.ts` that track any user input that would change the map extent (e.g. `mouse-wheel`, `drag`). Pass these back to `MapView` in a consolidated event, something like `OnExtentChanged`, with the new `Extent`. Expose as a handler for consuming code to listen.

**Comment by TimPurdum** [comment]
This should also handle a programmatic extent change, such as when a home or locator widget is clicked.

**Comment by morehavoc** [comment]
I'm not sure what the correct set of events is here, but we should be careful. For example, I don't think that `mouse-wheel` will fire if you are zooming using a touch screen.

One thing to do here would be just implementing these events so that folks can get the information from them to use as they see fit. A unified `OnExtentChanged` would be really useful! But might be hard to handle b/c we want that to work across all screen types. We should confirm what the events are for all of those before we dive into that unified event.

**Comment by TimPurdum** [comment]
[This](https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html#events-summary) gives us the full event list, I believe, or at least what Esri is documenting and likely to support. Again, I agree, we should expose the individual events as well as the unified extent change event.

**Comment by morehavoc** [comment]
I had to go remember how this works. These events are misleading, they are essentially the standard html events. To get the real events that we are talking about here we need to actually subscribe to property changes(much like an MVVM pattern in dotnet).

https://developers.arcgis.com/javascript/latest/api-reference/esri-core-reactiveUtils.html

check out this part of the API docs for how that works, but basically you can wait for a property like ‘stationary’ to be false ( the map is moving) and then watch for some other property to change. One complexity here is that something like extent will change multiple times in one zoom or pan action. 

Here’s a sample I found online (it’s old so we should double check it) https://community.esri.com/t5/arcgis-api-for-javascript-questions/in-4-x-how-to-catch-quot-extent-change-quot-event/td-p/215837

so, likely we need to mimic this event/property pattern in some way.

**Comment by Sipowiz** [comment]
I think it would be a good basic principle to keep the events uniform with the JS api so events would be available in same (corresponding dotnet class / component) objects as they are in JS api and returning similiarly structured event args with same properties and types as the original event. Maybe some object properties can be stripped away if they make no sense in blazor side of things.

Events that keep firing constantly as they happen for example "pan", should have a "waiter" argument in the jsInterop layer of some sort that prevents event flooding to dotnet side. This could affect performance since event args have to be serialized everytime. This waiter could be "eventsettings" object that can be set as parameter to component and it would have int? property for all constantly firing events in that object. ie.

```
class EventSettings{
public int? OnPanFireWaitTime { get; set; }
public int? OnZoomFireWaitTime {get; set;}
}
```
If int value is null there is no wait time and corresponding event fires constantly. If there is a value, that is the wait time in milliseconds. Basically what the waiter should do imo is to wait for the setted time and fire the event in dotnet side after that. If another same event comes in from JS side before the timer, the timer gets restarted.

**Comment by Sipowiz** [comment]
OnExtentChange is definitely something that should be available. Seems that JS api has implemented this in version 3.x but it's not there anymore in 4. versions. ‘stationary’ link that @morehavoc provided is a good place to start.

**Comment by TimPurdum** [comment]
> Events that keep firing constantly as they happen for example "pan", should have a "waiter" argument in the jsInterop layer of some sort that prevents event flooding to dotnet side.

@Sipowiz thanks for joining the conversation here. This is a neat idea. One thing we discussed internally is that quick events like `pan` and `pointer-move` make a big difference if you are running locally (WASM or MAUI) vs. Blazor Server, where every communication is a SignalR message. That makes lag noticeable if you are listening constantly for changes, so I like your suggestion of setting a "rate limiter" on passing these events back to .NET.

**Comment by Shawn-Fan** [comment]
@TimPurdum 
I have a question on Dymaptic in Blazor Server. can you explain what your point of view on Dymaptic library works in Blazor server. In my view, it should work almost the same way as Blazor WASM although the communication type is different.

**Comment by TimPurdum** [comment]
> 

@Shawn-Fan correct, yes, it works essentially the same in both Blazor Server and Blazor WASM. The samples in this repo have an example of both, and they are tested fairly regularly.
