### ISSUE TITLE
Support Graphics added to FeatureLayer

### ISSUE THREAD

**Issue by TimPurdum** [dymaptic/GeoBlazor#92]
According to the [Feature Layer](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html) JS docs, a `Feature` in ArcGIS JS is just a `Graphic`.

- Add the ability to add and register Graphics as subcomponents of `FeatureLayer`
- Alter add, remove, and update logic for graphics to make sure it handles feature layer graphics as well as `GraphicLayer` graphics and those placed directly on `MapView`.

**Comment by morehavoc** [comment]
While that's true, A Feature Layer represents a database table. So we wouldn't want to just "register" graphics as a subcomponent of a FeatureLayer. Would those Graphics being added go to the actual layer (database table)? We do want to support add/update/delete methods on these though so that you could programmatically get a Graphic, edit attributes, and then update the FeatureLayer.

Note that the edit tools are doing this already, but that's a UI component, I'm thinking more of a way to do this in code so that you could have a custom UI or some other custom process that is updating data.

**Comment by TimPurdum** [comment]
This is for in-memory, or on-client rendering. [Here](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html#client-side) is the exact section I was referring to, `Add an array of client-side Features`. I think the idea is that this is used _in place of_ a url to a feature service. Since it's all client-side, I don't think a database is involved.

**Comment by morehavoc** [comment]
Ohh, I see! Okay, yeah, this would be nice to have b/c it is kind of simulating your own "database table" with a schema and stuff. This would be especially useful if we could construct a way to connect it directly with a set of c# objects. So I'm thinking that you create an `ObservableCollection<T>` (or something like that) and then that gets mapped directly to the FeatureLayer for you, and you don't need to do much other than add/remove/edit things on that collection and they are synced to the map. 

I'm not sure this is a good idea yet, but worth discussion.
